import groovy.json.JsonOutput

pipeline {
    agent {
		docker {
			image 'maven:3.5-jdk-8'
			args '-v $HOME/.m2:/root/.m2'
		}
	}
	stages {
		stage('Build') {
			steps {
				echo 'Building #${env.BUILD_ID}...'
				sh 'mvn -v'
				sh 'ls -al'
			}
		}
		stage('Test') {
			steps {
				echo 'Testing...'
			}
		}
		stage('Publish') {
			steps {
				echo 'Publishing...'
			}
		}
   }
   post {
		always {
			echo 'post section...'
		}
		failure {
			echo 'failure...'
		}
   }
}