import groovy.json.JsonOutput

pipeline {
    agent {
		docker {
			image 'maven:3.5-jdk-8'
			args '-v $HOME/.m2:/root/.m2'
		}
	}
	stages {
		stage('Build') {
			steps {
				echo 'Building #${env.BUILD_NUMBER}...'
				sh 'cd evalib-server && mvn clean package'
			}
		}
		stage('Test') {
			steps {
				echo 'Testing...'
			}
		}
		stage('Docker') {
			steps {
				echo 'Building the docker image...'				
				def image = docker.build("evalib-service", "-t ${env.BUILD_NUMBER} -t latest -f evalib-server/docker/Dockerfile")				
			}
		}
   }
   post {
		always {
			echo 'post section...'
			archiveArtifacts artifacts: 'evalib-server/evalib-web-admin/target/*.jar'
		}
		failure {
			echo 'failure...'
		}
   }
}