import groovy.json.JsonOutput

pipeline {
    agent any	
	stages {
		stage('Build') {
			steps {
				echo 'Building...'
                echo "Running ${env.BUILD_ID} on ${env.JENKINS_URL}"
			}
		}
		stage('Test') {
			steps {
				echo 'Testing...'
			}
		}
		stage('Publish') {
			steps {
				echo 'Publishing...'
			}
		}
   }
   post {
		always {
			echo 'post section...'
		}
		failure {
			echo 'failure...'
		}
   }
}