export const GET_USERS = "GET_USERS";

export const EVALUATION_CREATE = "EVALUATION_CREATE";
export const EVALUATION_UPDATE = "EVALUATION_UPDATE";
export const EVALUATION_DELETE = "EVALUATION_DELETE";