export const GET_USERS = "GET_USERS";

export const EVALUATION_CREATE = "EVALUATION_CREATE";
export const EVALUATION_UPDATE = "EVALUATION_UPDATE";
export const EVALUATION_DELETE = "EVALUATION_DELETE";

export const EVALUATION_QUESTION_ADD = "EVALUATION_QUESTION_ADD";
export const EVALUATION_QUESTION_UPDATE = "EVALUATION_QUESTION_UPDATE";
export const EVALUATION_QUESTION_DELETE = "EVALUATION_QUESTION_DELETE"