export const GET_USERS = "GET_USERS";

export const EVALUATION_CREATE = "EVALUATION_CREATE";
export const EVALUATION_UPDATE = "EVALUATION_UPDATE";
export const EVALUATION_DELETE = "EVALUATION_DELETE";

export const EVALUATION_CHOICEQUESTION_ADD = "EVALUATION_CHOICEQUESTION_ADD";
export const EVALUATION_CHOICEQUESTION_UPDATE = "EVALUATION_CHOICEQUESTION_UPDATE";
export const EVALUATION_CHOICEQUESTION_DELETE = "EVALUATION_CHOICEQUESTION_DELETE"