export const GET_USERS = "GET_USERS";

export const EVALUATION_CREATE = "EVALUATION_CREATE";
export const EVALUATION_UPDATE = "EVALUATION_UPDATE";
export const EVALUATION_DELETE = "EVALUATION_DELETE";

export const EVALUATION_SUBJECT_ADD = "EVALUATION_SUBJECT_ADD";
export const EVALUATION_SUBJECT_UPDATE = "EVALUATION_SUBJECT_UPDATE";
export const EVALUATION_SUBJECT_DELETE = "EVALUATION_SUBJECT_DELETE"

export const SINGLE_CHOICE_QUESTION = "singleChoiceQuestion";
export const MULTIPLE_CHOICE_QUESTION = "multipleChoiceQuestion";