package tech.yhao.evalib.core.dao;

import java.util.List;
import java.util.UUID;
import tech.yhao.evalib.core.model.ChoiceQuestion;

public interface ChoiceQuestionDao {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table public.t_choice_question
	 *
	 * @mbg.generated Wed Aug 22 13:45:02 CST 2018
	 */
	int deleteByPrimaryKey(UUID id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table public.t_choice_question
	 *
	 * @mbg.generated Wed Aug 22 13:45:02 CST 2018
	 */
	int insert(ChoiceQuestion record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table public.t_choice_question
	 *
	 * @mbg.generated Wed Aug 22 13:45:02 CST 2018
	 */
	ChoiceQuestion selectByPrimaryKey(UUID id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table public.t_choice_question
	 *
	 * @mbg.generated Wed Aug 22 13:45:02 CST 2018
	 */
	List<ChoiceQuestion> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table public.t_choice_question
	 *
	 * @mbg.generated Wed Aug 22 13:45:02 CST 2018
	 */
	int updateByPrimaryKey(ChoiceQuestion record);

	/**
	 * Query the questions by evaluation id. 
	 * @param evaluationId: The evaluation id.
	 * @return {@link ChoiceQuestion} list.
	 */
	List<ChoiceQuestion> selectByEvaluationId(UUID evaluationId);
}