package tech.yhao.evalib.core.dao;

import java.util.List;
import java.util.UUID;
import tech.yhao.evalib.core.model.Evaluation;

public interface EvaluationDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_evaluation
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    int deleteByPrimaryKey(UUID id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_evaluation
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    int insert(Evaluation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_evaluation
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    Evaluation selectByPrimaryKey(UUID id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_evaluation
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    List<Evaluation> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_evaluation
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    int updateByPrimaryKey(Evaluation record);
    
    /**
     * Select the {@link Evaluation} and with {@link ChoiceQuestion} list by the evaluation id.
     * @param id : The evaluation id. 
     * @return the {@link Evaluation} and with {@link ChoiceQuestion} list.
     */
    Evaluation selectByPrimaryKeyWithQuestionInfo(UUID id);
}