package tech.yhao.evalib.core.dao;

import java.util.List;
import java.util.UUID;
import tech.yhao.evalib.core.model.Login;

public interface LoginDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_login
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    int deleteByPrimaryKey(UUID id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_login
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    int insert(Login record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_login
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    Login selectByPrimaryKey(UUID id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_login
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    List<Login> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_login
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    int updateByPrimaryKey(Login record);
}