package tech.yhao.evalib.core.dao;

import java.util.List;
import java.util.UUID;
import tech.yhao.evalib.core.model.Permission;

public interface PermissionDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_permission
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    int deleteByPrimaryKey(UUID id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_permission
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    int insert(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_permission
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    Permission selectByPrimaryKey(UUID id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_permission
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    List<Permission> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_permission
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    int updateByPrimaryKey(Permission record);
}