package tech.yhao.evalib.core.dao;

import java.util.List;
import java.util.UUID;
import tech.yhao.evalib.core.model.Role;

public interface RoleDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_role
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    int deleteByPrimaryKey(UUID id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_role
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_role
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    Role selectByPrimaryKey(UUID id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_role
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    List<Role> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_role
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    int updateByPrimaryKey(Role record);
}