package tech.yhao.evalib.core.model;

import java.util.Date;
import java.util.UUID;

public class ChoiceQuestion {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_choice_question.id
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    private UUID id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_choice_question.description
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_choice_question.choice_type
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    private ChoiceType choiceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_choice_question.created_at
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_choice_question.updated_at
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_choice_question.created_by
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    private UUID createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_choice_question.evaluation_id
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    private Object evaluationId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_choice_question.id
     *
     * @return the value of public.t_choice_question.id
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    public UUID getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_choice_question.id
     *
     * @param id the value for public.t_choice_question.id
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_choice_question.description
     *
     * @return the value of public.t_choice_question.description
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_choice_question.description
     *
     * @param description the value for public.t_choice_question.description
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_choice_question.choice_type
     *
     * @return the value of public.t_choice_question.choice_type
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    public ChoiceType getChoiceType() {
        return choiceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_choice_question.choice_type
     *
     * @param choiceType the value for public.t_choice_question.choice_type
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    public void setChoiceType(ChoiceType choiceType) {
        this.choiceType = choiceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_choice_question.created_at
     *
     * @return the value of public.t_choice_question.created_at
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_choice_question.created_at
     *
     * @param createdAt the value for public.t_choice_question.created_at
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_choice_question.updated_at
     *
     * @return the value of public.t_choice_question.updated_at
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_choice_question.updated_at
     *
     * @param updatedAt the value for public.t_choice_question.updated_at
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_choice_question.created_by
     *
     * @return the value of public.t_choice_question.created_by
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    public UUID getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_choice_question.created_by
     *
     * @param createdBy the value for public.t_choice_question.created_by
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    public void setCreatedBy(UUID createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_choice_question.evaluation_id
     *
     * @return the value of public.t_choice_question.evaluation_id
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    public Object getEvaluationId() {
        return evaluationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_choice_question.evaluation_id
     *
     * @param evaluationId the value for public.t_choice_question.evaluation_id
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    public void setEvaluationId(Object evaluationId) {
        this.evaluationId = evaluationId;
    }
}