package tech.yhao.evalib.core.model;

import java.util.Date;
import java.util.UUID;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_user.id
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    private UUID id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_user.name
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_user.first_name
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_user.last_name
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_user.birthday
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_user.sex
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    private Sex sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_user.email_address
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    private String emailAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_user.phone
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_user.city
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_user.avatar_url
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    private String avatarUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_user.description
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_user.created_at
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_user.updated_at
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_user.id
     *
     * @return the value of public.t_user.id
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    public UUID getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_user.id
     *
     * @param id the value for public.t_user.id
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_user.name
     *
     * @return the value of public.t_user.name
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_user.name
     *
     * @param name the value for public.t_user.name
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_user.first_name
     *
     * @return the value of public.t_user.first_name
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_user.first_name
     *
     * @param firstName the value for public.t_user.first_name
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_user.last_name
     *
     * @return the value of public.t_user.last_name
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_user.last_name
     *
     * @param lastName the value for public.t_user.last_name
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_user.birthday
     *
     * @return the value of public.t_user.birthday
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_user.birthday
     *
     * @param birthday the value for public.t_user.birthday
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_user.sex
     *
     * @return the value of public.t_user.sex
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    public Sex getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_user.sex
     *
     * @param sex the value for public.t_user.sex
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    public void setSex(Sex sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_user.email_address
     *
     * @return the value of public.t_user.email_address
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    public String getEmailAddress() {
        return emailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_user.email_address
     *
     * @param emailAddress the value for public.t_user.email_address
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_user.phone
     *
     * @return the value of public.t_user.phone
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_user.phone
     *
     * @param phone the value for public.t_user.phone
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_user.city
     *
     * @return the value of public.t_user.city
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_user.city
     *
     * @param city the value for public.t_user.city
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_user.avatar_url
     *
     * @return the value of public.t_user.avatar_url
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_user.avatar_url
     *
     * @param avatarUrl the value for public.t_user.avatar_url
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_user.description
     *
     * @return the value of public.t_user.description
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_user.description
     *
     * @param description the value for public.t_user.description
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_user.created_at
     *
     * @return the value of public.t_user.created_at
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_user.created_at
     *
     * @param createdAt the value for public.t_user.created_at
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_user.updated_at
     *
     * @return the value of public.t_user.updated_at
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_user.updated_at
     *
     * @param updatedAt the value for public.t_user.updated_at
     *
     * @mbg.generated Wed Aug 22 13:45:02 CST 2018
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}